"""delete gender and dob from user

Revision ID: 15776219a8fa
Revises: 59412fb3aba7
Create Date: 2026-02-24 01:41:41.827108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15776219a8fa'
down_revision: Union[str, Sequence[str], None] = '59412fb3aba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'gender')
    op.drop_column('User', 'Date_of_Birth')
    op.drop_column('User', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('full_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('Date_of_Birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('gender', sa.VARCHAR(length=6, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
