"""add origin and des airport

Revision ID: 284058bd93ba
Revises: 69906118c145
Create Date: 2026-02-20 05:12:18.427821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284058bd93ba'
down_revision: Union[str, Sequence[str], None] = '69906118c145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flight', sa.Column('origin_city_id', sa.Integer(), nullable=True))
    op.add_column('Flight', sa.Column('destination_city_id', sa.Integer(), nullable=True))
    op.alter_column('Flight', 'Airport_ID',
                    existing_type=sa.Integer(),
               nullable=False)
    op.create_foreign_key(None, 'Flight', 'Airport', ['destination_city_id'], ['Airport_ID'])
    op.create_foreign_key(None, 'Flight', 'Airport', ['origin_city_id'], ['Airport_ID'])
    op.create_foreign_key(None, 'Flight', 'Airport', ['Airport_ID'], ['Airport_ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Flight', type_='foreignkey')
    op.drop_constraint(None, 'Flight', type_='foreignkey')
    op.drop_constraint(None, 'Flight', type_='foreignkey')
    op.alter_column('Flight', 'Airline_ID',
               nullable=True)
    op.drop_column('Flight', 'destination_city_id')
    op.drop_column('Flight', 'origin_city_id')
    # ### end Alembic commands ###
