"""deleted user and passenger relationships

Revision ID: 28c3e8a602ef
Revises: 6152d283e833
Create Date: 2026-02-26 21:37:37.641473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c3e8a602ef'
down_revision: Union[str, Sequence[str], None] = '6152d283e833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__User__Passenger___1AD3FDA4'), 'User', type_='foreignkey')
    op.drop_column('User', 'Passenger_ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('Passenger_ID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('FK__User__Passenger___1AD3FDA4'), 'User', 'Passenger', ['Passenger_ID'], ['Passenger_ID'])
    # ### end Alembic commands ###
