"""drop email unigue

Revision ID: 3ce97f6c81a7
Revises: 435404a9867f
Create Date: 2026-04-28 18:56:07.753076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce97f6c81a7'
down_revision: Union[str, Sequence[str], None] = '435404a9867f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    'UQ_Passenger_Email',  
    'Passenger',
    type_='unique'
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
