"""drop aircraft table

Revision ID: 435404a9867f
Revises: 9678b17fad1a
Create Date: 2026-04-28 18:17:03.526258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435404a9867f'
down_revision: Union[str, Sequence[str], None] = '9678b17fad1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__Flight__Aircraft__74AE54BC'), 'Flight', type_='foreignkey')
    op.drop_column('Flight', 'Aircraft_ID')
    op.drop_constraint(op.f('FK__Aircraft__Airlin__619B8048'), 'Aircraft', type_='foreignkey')
    op.drop_column('Aircraft', 'Airline_ID')
    op.drop_table('Aircraft')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flight', sa.Column('Aircraft_ID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('FK__Flight__Aircraft__74AE54BC'), 'Flight', 'Aircraft', ['Aircraft_ID'], ['Aircraft_ID'])
    # ### end Alembic commands ###
