"""add and delete columns

Revision ID: 51f9349ea6a3
Revises: 15776219a8fa
Create Date: 2026-02-25 02:42:45.022637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f9349ea6a3'
down_revision: Union[str, Sequence[str], None] = '15776219a8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Passenger', sa.Column('Reservation_ID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Passenger', 'Reservation', ['Reservation_ID'], ['Reservation_ID'])
    op.add_column('Reservation', sa.Column('User_ID', sa.Integer(), nullable=True))
    op.add_column('Reservation', sa.Column('Flight_ID', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('FK__Reservati__Passe__5535A963'), 'Reservation', type_='foreignkey')
    op.drop_constraint(op.f('CK__Reservati__Payme__5441852A'), 'Reservation', type_='check')
    op.create_foreign_key(None, 'Reservation', 'User', ['User_ID'], ['User_ID'])
    op.create_foreign_key(None, 'Reservation', 'Flight', ['Flight_ID'], ['Flight_ID'])
    op.drop_column('Reservation', 'Passenger_ID')
    op.drop_column('Reservation', 'Payment_Status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reservation', sa.Column('Payment_Status', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Reservation', sa.Column('Passenger_ID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Reservation', type_='foreignkey')
    op.drop_constraint(None, 'Reservation', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Reservati__Passe__5535A963'), 'Reservation', 'Passenger', ['Passenger_ID'], ['Passenger_ID'])
    op.drop_column('Reservation', 'Flight_ID')
    op.drop_column('Reservation', 'User_ID')
    op.drop_constraint(None, 'Passenger', type_='foreignkey')
    op.drop_column('Passenger', 'Reservation_ID')
    # ### end Alembic commands ###
