"""add airline fk

Revision ID: 59412fb3aba7
Revises: 284058bd93ba
Create Date: 2026-02-23 04:28:26.092117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Integer


# revision identifiers, used by Alembic.
revision: str = '59412fb3aba7'
down_revision: Union[str, Sequence[str], None] = '284058bd93ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Flight', 'Airline_ID', existing_type=Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Flight', 'Airline_ID', existing_type=Integer(),
               nullable=True)
    # ### end Alembic commands ###
