"""delete pilot fk

Revision ID: 5d465d473df4
Revises: c3045c8d4e80
Create Date: 2026-04-27 22:38:01.493847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d465d473df4'
down_revision: Union[str, Sequence[str], None] = 'c3045c8d4e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pilot', 'Airline_ID')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pilot', sa.Column('Airline_ID', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
