"""add price and airline to flight

Revision ID: 69906118c145
Revises: c080793c0346
Create Date: 2026-02-19 02:36:21.714671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69906118c145'
down_revision: Union[str, Sequence[str], None] = 'c080793c0346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flight', sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Flight', sa.Column('Airline_ID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Flight', 'Airline', ['Airline_ID'], ['Airline_ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Flight', type_='foreignkey')
    op.drop_column('Flight', 'Airline_ID')
    op.drop_column('Flight', 'Price')
    # ### end Alembic commands ###
