"""add two columns to user

Revision ID: 6abc5bc03fe0
Revises: 3ce97f6c81a7
Create Date: 2026-04-28 20:35:06.519925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6abc5bc03fe0'
down_revision: Union[str, Sequence[str], None] = '3ce97f6c81a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('Reset_Token', sa.String(), nullable=True))
    op.add_column('User', sa.Column('Reset_Token_Expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'Reset_Token_Expiry')
    op.drop_column('User', 'Reset_Token')
    # ### end Alembic commands ###
