"""delete reservation status

Revision ID: 8c81a2f83e0f
Revises: 28c3e8a602ef
Create Date: 2026-02-26 22:16:41.781396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c81a2f83e0f'
down_revision: Union[str, Sequence[str], None] = '28c3e8a602ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('CK__Reservati__Reser__534D60F1', 'Reservation', type_='check')
    op.drop_column('Reservation', 'Reservation_Status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reservation', sa.Column('Reservation_Status', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.create_check_constraint('CK__Reservati__Reser__534D60F1', "Reservation', 'Reservation_Status IN ('Pending','Confirmed','Cancelled)')")
    # ### end Alembic commands ###
