"""drop baggage table

Revision ID: 9678b17fad1a
Revises: 9e46b88aa6d7
Create Date: 2026-04-28 14:59:26.626598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9678b17fad1a'
down_revision: Union[str, Sequence[str], None] = '9e46b88aa6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__Flight__76969D2E'), 'Flight', type_='foreignkey')
    op.drop_constraint(op.f('FK__Flight_St__Staff__09A971A2'), 'Flight_Staff', type_='foreignkey')
    op.drop_constraint(op.f('FK__Flight_St__Fligh__08B54D69'), 'Flight_Staff', type_='foreignkey')
    op.drop_constraint(op.f('FK__Flight_Cr__Crew___05D8E0BE'), 'Flight_Crew', type_='foreignkey')
    op.drop_constraint(op.f('FK__Flight_Cr__Fligh__04E4BC85'), 'Flight_Crew', type_='foreignkey')
    op.drop_constraint(op.f('FK__Ground_Staff__6EF57B66'), 'Ground_Staff', type_='foreignkey')
    op.drop_constraint(op.f('FK__Gate__6A30C649'), 'Gate', type_='foreignkey')
    op.drop_constraint(op.f('FK__Terminal__Airpor__66603565'), 'Terminal', type_='foreignkey')
    op.drop_constraint(op.f('FK__Cabin_Cre__Airli__4E88ABD4'), 'Cabin_Crew', type_='foreignkey')
    op.drop_constraint(op.f('FK__Baggage__Ticket___02084FDA'), 'Baggage', type_='foreignkey')
    op.drop_table('Ground_Staff')
    op.drop_table('Flight_Staff')
    op.drop_table('Gate')
    op.drop_table('Flight_Crew')
    op.drop_table('Terminal')
    op.drop_table('Baggage')
    op.drop_table('Cabin_Crew')
    





    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('FK__Flight__76969D2E'), 'Flight', 'Gate', ['Terminal_Number', 'Airport_ID', 'Gate_Number'], ['Terminal_Number', 'Airport_ID', 'Gate_Number'])
    op.create_table('Cabin_Crew',
    sa.Column('Crew_ID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Crew_Name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Crew_Role', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Experience_Years', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Crew_Status', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Contact_Number', sa.VARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Airline_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Airline_ID'], ['Airline.Airline_ID'], name=op.f('FK__Cabin_Cre__Airli__4E88ABD4')),
    sa.PrimaryKeyConstraint('Crew_ID', name=op.f('PK__Cabin_Cr__B383F0572F2D33D3'))
    )
    op.create_table('Baggage',
    sa.Column('Baggage_Number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Baggage_Weight', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('Bag_Type', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Ticket_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Ticket_ID'], ['Ticket.Ticket_ID'], name=op.f('FK__Baggage__Ticket___02084FDA')),
    sa.PrimaryKeyConstraint('Ticket_ID', 'Baggage_Number', name=op.f('PK__Baggage__B0C1709DF38A3F89'))
    )
    op.create_table('Terminal',
    sa.Column('Terminal_Number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Terminal_Type', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Terminal_Capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Airport_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Airport_ID'], ['Airport.Airport_ID'], name=op.f('FK__Terminal__Airpor__66603565')),
    sa.PrimaryKeyConstraint('Airport_ID', 'Terminal_Number', name=op.f('PK__Terminal__C29032AE3D7ACAD9'))
    )
    op.create_table('Flight_Crew',
    sa.Column('Flight_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Crew_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Cabin_Crew_Name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Crew_ID'], ['Cabin_Crew.Crew_ID'], name=op.f('FK__Flight_Cr__Crew___05D8E0BE')),
    sa.ForeignKeyConstraint(['Flight_ID'], ['Flight.Flight_ID'], name=op.f('FK__Flight_Cr__Fligh__04E4BC85')),
    sa.PrimaryKeyConstraint('Flight_ID', 'Crew_ID', name=op.f('PK__Flight_C__A1F9DB8ACF9CEFAE'))
    )
    op.create_table('Gate',
    sa.Column('Gate_Number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Gate_Status', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Terminal_Number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Airport_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Airport_ID', 'Terminal_Number'], ['Terminal.Airport_ID', 'Terminal.Terminal_Number'], name=op.f('FK__Gate__6A30C649')),
    sa.PrimaryKeyConstraint('Terminal_Number', 'Airport_ID', 'Gate_Number', name=op.f('PK__Gate__84C8CDFEBC30D555'))
    )
    op.create_table('Flight_Staff',
    sa.Column('Flight_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Staff_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Staff_Name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Flight_ID'], ['Flight.Flight_ID'], name=op.f('FK__Flight_St__Fligh__08B54D69')),
    sa.ForeignKeyConstraint(['Staff_ID'], ['Ground_Staff.Staff_ID'], name=op.f('FK__Flight_St__Staff__09A971A2')),
    sa.PrimaryKeyConstraint('Flight_ID', 'Staff_ID', name=op.f('PK__Flight_S__E9ECFBB3351CB162'))
    )
    op.create_table('Ground_Staff',
    sa.Column('Staff_ID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Staff_Name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Staff_Role', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Staff_Shift', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Contact_Number', sa.VARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Terminal_Number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Airport_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Airport_ID', 'Terminal_Number'], ['Terminal.Airport_ID', 'Terminal.Terminal_Number'], name=op.f('FK__Ground_Staff__6EF57B66')),
    sa.PrimaryKeyConstraint('Staff_ID', name=op.f('PK__Ground_S__32D1F3C36C42AF08'))
    )
    # ### end Alembic commands ###
