"""added tokens table

Revision ID: c080793c0346
Revises: 9b3eef6aa628
Create Date: 2026-02-12 05:31:45.685264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import DateTime, String


# revision identifiers, used by Alembic.
revision: str = 'c080793c0346'
down_revision: Union[str, Sequence[str], None] = '9b3eef6aa628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tokens',
    sa.Column('tokens_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.User_ID'], ),
    sa.PrimaryKeyConstraint('tokens_id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('Flight', 'Arrival_Time', existing_type=DateTime(),
               nullable=False)
    op.alter_column('Flight', 'Departure_Time', existing_type=DateTime(),
               nullable=False)
    op.alter_column('Flight', 'FlightStatus', existing_type=String(10),
               nullable=False,
               existing_server_default=sa.text("('Scheduled')"))
    op.drop_column('Passenger', 'Hashed_Password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Passenger', sa.Column('Hashed_Password', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.alter_column('Flight', 'FlightStatus', existing_type=String(10),
               nullable=True,
               existing_server_default=sa.text("('Scheduled')"))
    op.alter_column('Flight', 'Departure_Time', existing_type=DateTime(),
               nullable=True)
    op.alter_column('Flight', 'Arrival_Time', existing_type=DateTime(),
               nullable=True)
    op.drop_table('Tokens')
    # ### end Alembic commands ###
